### PR TITLE
Add eachLike array flexible matcher

### PR DESCRIPTION
**Pull request by michaelisgro**
Added Pact.Match.eachLike matcher.

Note: this build will not pass until https://github.com/bethesque/pact-support/pull/10 has been incorporated into the next gem versions (pact-support and pact-mock-service) and we update the Gemfile. 

cc: @mefellows

### CODE REVIEW

**Comment by bethesque** [comment]
Happy to merge once the Travis CI build is passing - can you investigate @michaelisgro? I've released a new version of pact-support, so it should have been picked up.

**Comment by mefellows** [comment]
@michaelisgro Run `bundle update pact-support` and commit the updated `Gemfile.lock`. Just tested locally on your branch and tests pass.

**Comment by michaelisgro** [comment]
Updated to check that eachLike minimum is greater than 0

cc: @mefellows

**Comment by bethesque** [comment]
@michaelisgro I can't see another commit, there's only one in the history.

**Comment by mefellows** [comment]
We squashed it  - but the change is in [there](https://github.com/DiUS/pact-consumer-js-dsl/pull/45/files#diff-67519ab8f184e6a99d14d33b9bb2f299R36) :)

**Comment by davidchin** [comment]
@bethesque I saw you bumped bower.json to v0.2.1, which contains this change. However, I think you probably forgot to tag it on Github. Could you please tag it so that it works with bower install? Thanks!

**Comment by mefellows** [comment]
@davidchin done.

**Pull request merged**
