### PR TITLE
Fixing the build to work for web/node, adding a few tweaks to the gulpfile to run some tasks in series instead of parallel

### PR DESCRIPTION
**Pull request by mboudreau**

### CODE REVIEW

**Comment by bethesque** [comment]
Thanks!

**Comment by bethesque** [comment]
Hi Michael,

I've merged and done a npm install, but when I run gulp, I get this error:

```
pact-consumer-js-dsl $ node_modules/.bin/gulp

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bethanyskurrie/workspace/rea/biq/pact-consumer-js-dsl/gulpfile.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by mboudreau** [comment]
Ah, sorry, forgot to include that plugin in the packages.json.  I just added it and pushed it.  Do another npm install and try again.

**Comment by mboudreau** [comment]
@bethesque I've also fixed the UMD template a bit better based on @BenSayers comments

**Comment by bethesque** [comment]
Is that in regards to the global require('xhr2'); ? I just trawled through the diff, and I can't see where that's been changed.

**Comment by mboudreau** [comment]
@bethesque Yes.  It used be in the umd-template.js file, which is now deleted (it was only being used to add that global var) and the require has been added to the http.js file to get better scoping with a nodejs conditional. 

I didn't see that you had merged my PR already, which is why you're not seeing it.  Here's the new PR with the new changes I've added.  This should fix everything.  

https://github.com/DiUS/pact-consumer-js-dsl/pull/30

**Pull request merged**
