### PR TITLE
Pact.Term and and SomethingLike flexible matchers.

### PR DESCRIPTION
**Pull request by mefellows**
This PR implements the DSL stolen from https://github.com/DiUS/pact-consumer-js-dsl/wiki/Flexible-matching. In summary:

* Introduced the `Pact.Match.term` and `Pact.Match.somethingLike` methods to the DSL
* Bumped `pack-mock-service` version to `0.7.0` (in both browser tests and example project) so that we can test against Pact2 specification
* Introduced a `run-browser-tests-pact2` task that executes the tests in the context of a mock service with the `--pact-specification-version 2` option, ensuring backwards / forwards compatibility of the DSL
* Updated main Readme to include flexible matching

### CODE REVIEW

**Comment by bethesque** [comment]
Thanks Matt!

**Comment by mefellows** [comment]
Awesome thanks!

**Comment by davidchin** [comment]
Nice work on getting this merged! :smile: Are you guys planning on releasing a new version including this change?

**Comment by bethesque** [comment]
Released 0.2.0

**Pull request merged**
